name: Node CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/node-setup@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, lint, and test
      run: |
        yarn install
        yarn lint
        yarn test
      env:
        CI: true